### ISSUE TITLE
Recombination Rates

### ISSUE THREAD

**Issue by hkmanching** [maizeatlas/saegus#1]
Function used to create list of crossover probabilities is specific to Tuson Data format (needs the following headers to work: locus, chr, agpv2, cM, namZmPRDA, namZmPRDS). I think it would be useful to create a function that only needs 3 necessary headers to run (locus, chr, cM) and can be applied to any marker set.

**Comment by maizeatlas** [comment]
This pertained to parser.py.  The input file should include chr and cM. Additional columns but will now be ignored by parser.py.
